source = ~/.config/hypr/rose-pine-hyprland/dist/legacy/rose-pine-moon.conf
background=$base
base=$surface
alternate_base=$overlay
text=$text
bright_text=$subtle
accent=$iris
accent_secondary=$foam
icon_theme=rose-pine-moon